"""Adaptive launcher icon foreground as a VectorDrawable (sharp at any size).

Same geometry as design/k.pen "App Icon" and lib/ui/widgets/rosette.dart:
house rosette bands (hypotrochoids, 6 lobes) + two outer rings in paper
white, a bg-coloured core disc, and "k" in Archivo Bold (outline taken from
the bundled variable font). Fits the 66dp safe circle of the 108dp canvas.

Also writes standalone icons (design proportions: rosette 74% of the
width) to design/icon/: k-icon.svg and, on macOS, 1024px PNGs rendered by
Quick Look — square full-bleed and rounded.

Run from the repo root (needs fontTools):
    python3 tool/app_icon.py
"""

import math
import shutil
import struct
import subprocess
import tempfile
import zlib
from pathlib import Path

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "android/app/src/main/res/drawable/ic_launcher_foreground.xml"
ICON_DIR = ROOT / "design/icon"
ICON_PX = 1024
ROSETTE_SHARE = 160 / 216  # design/k.pen App Icon: rosette / icon width

CANVAS = 108.0  # adaptive icon, dp
C = CANVAS / 2
ROSETTE_DP = 66.0  # safe circle diameter
EXTENT = 120.0  # rosette units: ±120
S = ROSETTE_DP / (2 * EXTENT)
STROKE_DP = 0.6
PAPER = "#ECEAE4"
BG = "#101114"
CORE_R = 12.5
K_SIZE = 18.0  # dp, font size of "k"

BANDS = [(80, 22, 5), (80, 30, 5), (80, 38, 5), (65, 18, 5), (65, 26, 5)]
RINGS = [118, 104]


def f(v: float) -> str:
    return f"{v:.3f}".rstrip("0").rstrip(".")


def band(a: float, d: float, k: int, steps: int = 720) -> str:
    pts = []
    for i in range(steps):
        t = i / steps * 2 * math.pi
        x = a * math.cos(t) + d * math.cos(k * t)
        y = a * math.sin(t) - d * math.sin(k * t)
        pts.append(f"{f(C + x * S)},{f(C + y * S)}")
    return "M" + " L".join(pts) + " Z"


def ring(r: float) -> str:
    r *= S
    return (
        f"M{f(C - r)},{f(C)} a{f(r)},{f(r)} 0 1,0 {f(2 * r)},0 "
        f"a{f(r)},{f(r)} 0 1,0 {f(-2 * r)},0 Z"
    )


def disc(r: float) -> str:
    return ring(r / S)


def k_glyph() -> str:
    font = TTFont(ROOT / "assets/fonts/Archivo.ttf")
    font = instantiateVariableFont(font, {"wght": 700, "wdth": 100})
    gs = font.getGlyphSet()
    name = font.getBestCmap()[ord("k")]
    upm = font["head"].unitsPerEm
    glyf = font["glyf"][name]
    glyf.recalcBounds(font["glyf"])
    x0, y0, x1, y1 = glyf.xMin, glyf.yMin, glyf.xMax, glyf.yMax
    sc = K_SIZE / upm
    # Centre the glyph's ink box on the core; flip y (font units are y-up).
    dx = C - (x0 + x1) / 2 * sc
    dy = C + (y0 + y1) / 2 * sc
    pen = SVGPathPen(gs, ntos=lambda v: f(v))
    gs[name].draw(TransformPen(pen, (sc, 0, 0, -sc, dx, dy)))
    return pen.getCommands()


def main() -> None:
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<!-- Generated by tool/app_icon.py from the design/k.pen App Icon. -->",
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        f'    android:width="{f(CANVAS)}dp"',
        f'    android:height="{f(CANVAS)}dp"',
        f'    android:viewportWidth="{f(CANVAS)}"',
        f'    android:viewportHeight="{f(CANVAS)}">',
    ]

    def stroke(d: str, alpha: float = 1.0) -> None:
        lines.append(
            f'    <path android:strokeColor="{PAPER}" '
            f'android:strokeWidth="{f(STROKE_DP)}" '
            + (f'android:strokeAlpha="{f(alpha)}" ' if alpha < 1 else "")
            + f'android:pathData="{d}" />'
        )

    strokes = [(band(a, d, k), 0.85) for a, d, k in BANDS]
    strokes += [(ring(r), 1.0) for r in RINGS]
    fills = [(disc(CORE_R), BG), (k_glyph(), PAPER)]
    for d, alpha in strokes:
        stroke(d, alpha)
    for d, color in fills:
        lines.append(f'    <path android:fillColor="{color}" android:pathData="{d}" />')
    lines.append("</vector>")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    standalone(strokes, fills)


def standalone(strokes, fills) -> None:
    box = ROSETTE_DP / ROSETTE_SHARE
    o = C - box / 2
    ICON_DIR.mkdir(parents=True, exist_ok=True)

    def svg(radius: float) -> str:
        body = [
            f'<svg xmlns="http://www.w3.org/2000/svg" width="{ICON_PX}" '
            f'height="{ICON_PX}" viewBox="{f(o)} {f(o)} {f(box)} {f(box)}">',
            f'<rect x="{f(o)}" y="{f(o)}" width="{f(box)}" height="{f(box)}" '
            f'rx="{f(radius * box)}" fill="{BG}"/>',
        ]
        for d, alpha in strokes:
            body.append(
                f'<path d="{d}" fill="none" stroke="{PAPER}" '
                f'stroke-width="{f(STROKE_DP)}" stroke-opacity="{f(alpha)}"/>'
            )
        for d, color in fills:
            body.append(f'<path d="{d}" fill="{color}"/>')
        return "".join(body) + "</svg>\n"

    variants = {"k-icon": 0.0, "k-icon-rounded": 48 / 216}
    for name, radius in variants.items():
        (ICON_DIR / f"{name}.svg").write_text(svg(radius))
    if not shutil.which("qlmanage"):
        print("qlmanage not found: SVGs only")
        return
    # Quick Look renders on white, so only the full-bleed square is rendered;
    # the rounded PNG is that square with an anti-aliased corner mask.
    with tempfile.TemporaryDirectory() as tmp:
        subprocess.run(
            ["qlmanage", "-t", "-s", str(ICON_PX), "-o", tmp,
             str(ICON_DIR / "k-icon.svg")],
            check=True, capture_output=True,
        )
        shutil.move(f"{tmp}/k-icon.svg.png", ICON_DIR / "k-icon.png")
    w, h, rgba = read_png(ICON_DIR / "k-icon.png")
    round_corners(w, h, rgba, variants["k-icon-rounded"] * w)
    write_png(ICON_DIR / "k-icon-rounded.png", w, h, rgba)
    print(f"wrote {ICON_DIR.relative_to(ROOT)}/k-icon(.png|-rounded.png|.svg)")


def read_png(path: Path) -> tuple[int, int, bytearray]:
    """8-bit RGB/RGBA PNG → (w, h, RGBA bytes)."""
    data = path.read_bytes()
    i, idat = 8, b""
    while i < len(data):
        n, kind = struct.unpack(">I4s", data[i : i + 8])
        chunk = data[i + 8 : i + 8 + n]
        if kind == b"IHDR":
            w, h, _, color = struct.unpack(">IIBB", chunk[:10])
        elif kind == b"IDAT":
            idat += chunk
        i += 12 + n
    raw = zlib.decompress(idat)
    bpp = 4 if color == 6 else 3
    stride = w * bpp
    out = bytearray()
    prev = bytearray(stride)
    pos = 0
    for _ in range(h):
        kind = raw[pos]
        line = bytearray(raw[pos + 1 : pos + 1 + stride])
        pos += 1 + stride
        for j in range(stride):
            a = line[j - bpp] if j >= bpp else 0
            b = prev[j]
            c = prev[j - bpp] if j >= bpp else 0
            if kind == 1:
                line[j] = (line[j] + a) & 255
            elif kind == 2:
                line[j] = (line[j] + b) & 255
            elif kind == 3:
                line[j] = (line[j] + (a + b) // 2) & 255
            elif kind == 4:
                pa, pb, pc = abs(b - c), abs(a - c), abs(a + b - 2 * c)
                pred = a if pa <= pb and pa <= pc else b if pb <= pc else c
                line[j] = (line[j] + pred) & 255
        prev = line
        if bpp == 4:
            out += line
        else:
            for k in range(0, stride, 3):
                out += line[k : k + 3] + b"\xff"
    return w, h, out


def round_corners(w: int, h: int, rgba: bytearray, r: float) -> None:
    """Alpha-mask the corners to radius r (4×4 supersampled coverage)."""
    n = math.ceil(r)
    for y in range(n):
        for x in range(n):
            inside = 0
            for sy in range(4):
                for sx in range(4):
                    dx = r - (x + (sx + 0.5) / 4)
                    dy = r - (y + (sy + 0.5) / 4)
                    if dx <= 0 or dy <= 0 or dx * dx + dy * dy <= r * r:
                        inside += 1
            alpha = inside / 16
            for cx, cy in ((x, y), (w - 1 - x, y), (x, h - 1 - y), (w - 1 - x, h - 1 - y)):
                k = (cy * w + cx) * 4 + 3
                rgba[k] = round(rgba[k] * alpha)


def write_png(path: Path, w: int, h: int, rgba: bytearray) -> None:
    def chunk(kind: bytes, body: bytes) -> bytes:
        return (
            struct.pack(">I", len(body)) + kind + body
            + struct.pack(">I", zlib.crc32(kind + body))
        )

    stride = w * 4
    raw = b"".join(
        b"\x00" + bytes(rgba[y * stride : (y + 1) * stride]) for y in range(h)
    )
    path.write_bytes(
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", struct.pack(">IIBBBBB", w, h, 8, 6, 0, 0, 0))
        + chunk(b"IDAT", zlib.compress(raw, 9))
        + chunk(b"IEND", b"")
    )


if __name__ == "__main__":
    main()
